//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalKhushBhojak
{
    using System;
    using System.Collections.Generic;
    
    public partial class Billing
    {
        public int BillingID { get; set; }
        public Nullable<int> ClientID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string CategoryID { get; set; }
        public Nullable<double> Hours { get; set; }
        public Nullable<int> RateID { get; set; }
        public Nullable<int> AttorneyID { get; set; }
    
        public virtual Attorney Attorney { get; set; }
        public virtual Category Category { get; set; }
        public virtual Client Client { get; set; }
        public virtual Rate Rate { get; set; }
    }
}
